// Flat FR/EN dictionary for the app's UI text. Only covers the screens/components
// translated so far (auth, Pokédex browsing, Pokémon detail, Settings) — see the
// language-toggle plan doc for what's still French-only regardless of locale.
// Extend this file (add keys to both `fr` and `en`) as more screens get translated;
// no architecture change needed for that.
export const STRINGS = {
  fr: {
    // Common
    'common.back': 'Retour',
    'common.email': 'Email',
    'common.password': 'Mot de passe',
    'common.save': 'Enregistrer',
    'common.copy': 'Copier',
    'common.error': 'Erreur',
    'common.copied': 'Copié',
    'common.cancel': 'Annuler',
    'common.choose': 'Choisir',
    'common.all': 'Tous',
    'common.clear': 'Effacer',
    'common.delete': 'Supprimer',
    'common.unpin': 'Désépingler',
    'common.close': 'Fermer',
    'common.refresh': 'Actualiser',
    'common.loadError': 'Impossible de charger ton profil, réessaie.',

    // App layout — global FABs
    'appLayout.a11ySettings': 'Réglages',
    'appLayout.a11yMarket': 'Marché',
    'appLayout.a11yInProgressTrade': 'Échange en cours',

    // Auth — login
    'auth.login.title': 'Connexion',
    'auth.login.submit': 'Se connecter',
    'auth.login.forgotPassword': 'Mot de passe oublié ?',
    'auth.login.noAccount': "Pas de compte ? S'inscrire",
    'auth.login.genericErr': 'Échec de la connexion',

    // Auth — signup
    'auth.signup.title': 'Créer un compte',
    'auth.signup.passwordPlaceholder': 'Mot de passe (min 6)',
    'auth.signup.usernamePlaceholder': 'Username (immutable, ex: tristan-42)',
    'auth.signup.checking': 'Vérification…',
    'auth.signup.available': 'Disponible ✓',
    'auth.signup.taken': 'Déjà pris',
    'auth.signup.invalidFormat': 'Format invalide',
    'auth.signup.displayNamePlaceholder': 'Nom affiché (public)',
    'auth.signup.submit': "S'inscrire",
    'auth.signup.haveAccount': 'Déjà un compte ? Se connecter',
    'auth.signup.legalPrefix': "En t'inscrivant, tu acceptes les",
    'auth.signup.legalTerms': 'CGU',
    'auth.signup.legalAnd': 'et la',
    'auth.signup.legalPrivacy': 'politique de confidentialité',
    'auth.signup.usernameInvalidMsg': 'Username invalide (3–30 caractères, a-z 0-9 _ - uniquement, doit commencer par a-z ou 0-9)',
    'auth.signup.usernameTakenErr': 'Ce username est déjà pris',
    'auth.signup.genericErr': 'Inscription échouée',
    'auth.signup.checkEmailTitle': 'Vérifie ta boîte mail',
    'auth.signup.checkEmailBody': 'On a envoyé un lien de confirmation à {email}. Clique dessus pour activer ton compte, puis connecte-toi.',
    'auth.signup.backToLogin': 'Retour à la connexion',

    // Settings
    'settings.usernameLabel': 'Username (immuable)',
    'settings.displayNameLabel': 'Nom affiché',
    'settings.publicProfileLabel': 'Profil public',
    'settings.darkThemeLabel': 'Thème sombre',
    'settings.languageLabel': 'Langue',
    'settings.paletteLabel': 'Palette de couleurs',
    'settings.animationsLabel': 'Animations',
    'settings.shareLinkLabel': 'Lien de partage',
    'settings.feedbackAdminLabel': 'Suggestions & tickets (admin)',
    'settings.feedbackLabel': 'Suggestions & bugs',
    'settings.logout': 'Se déconnecter',
    'settings.terms': "Conditions d'utilisation",
    'settings.privacy': 'Confidentialité',
    'settings.trainerFallback': 'Dresseur',
    'settings.displayNameEmpty': 'Le nom affiché ne peut pas être vide.',

    // Pokédex screen
    'pokedex.heroTitle': 'Pokédex National',
    'pokedex.filterHint': 'Filtre : {hint}',

    // Search / filter bar
    'search.placeholder': 'Rechercher (nom ou n°)',
    'search.owned': 'Possédés',
    'search.missing': 'Manquants',
    'search.filtersTitle': 'Filtres',
    'search.statusLabel': 'Statut',
    'search.sectionLabel': 'Génération / Type / Set / Rareté',
    'search.sortLabel': 'Tri',
    'search.resetFilters': 'Réinitialiser les filtres',
    'search.typeLabel': 'Type',
    'search.setLabel': 'Set',
    'search.setTcgTitle': 'Set TCG',
    'search.rarityLabel': 'Rareté',
    'search.generationLabel': 'Génération',
    'search.typeChip': 'Type: {value}',
    'search.typeChipCount': 'Type ({n})',
    'search.setChip': 'Set: {value}',
    'search.rarityChip': 'Rareté: {value}',
    'search.genChipCount': 'Génération ({n})',
    'search.a11yClear': 'Effacer la recherche',
    'search.a11yToggleSearch': 'Rechercher',
    'search.a11yToggleFilter': 'Filtrer',
    'search.a11yCycleColumns': 'Changer le nombre de colonnes',
    'search.a11yTogglePrice': 'Afficher les prix',

    // Card filter tree (extension filter)
    'cardFilter.title': 'Filtrer par extension',
    'cardFilter.selectedSingular': '{n} set sélectionné',
    'cardFilter.selectedPlural': '{n} sets sélectionnés',
    'cardFilter.otherSeries': 'Autres',
    'cardFilter.a11yJumpToSet': 'Aller à ce set',

    // Pokémon detail
    'pokemon.a11yFavorite': 'Ajouter aux favoris',
    'pokemon.a11yUnfavorite': 'Retirer des favoris',
    'pokemon.a11yShowcase': 'Ajouter à la vitrine',
    'pokemon.a11yUnshowcase': 'Retirer de la vitrine',
    'pokemon.a11yPrev': 'Pokémon précédent',
    'pokemon.a11yNext': 'Pokémon suivant',
    'pokemon.notFound': 'Pokémon inconnu',
    'pokemon.showcaseLimitToast': 'Vitrine limitée à {n} cartes — retire-en une avant d’en ajouter une autre.',
    'pokemon.noCardsKnown': 'Aucune carte TCG connue pour ce Pokémon dans la base.',
    'pokemon.noRegionCards': 'Aucune carte {region} connue pour ce Pokémon.',
    'pokemon.noCardsInSelectedSets': 'Aucune carte dans les extensions sélectionnées.',
    'pokemon.wishFilterActive': '♥ Filtre wish actif — tap pour tout voir',
    'pokemon.infoBanner': 'Les cartes possédées apparaissent déverrouillées. Touche une carte pour en faire ta carte choisie du Pokédex national.',
    'pokemon.chooseCardTitle': 'Choisir cette carte',
    'pokemon.chooseCardMessage': 'Faire de « {cardName} » ta carte choisie du Pokédex national pour {pokemonName} ?',
    'pokemon.addedOn': 'Ajoutée le {date}',
    'pokemon.regionGlobal': 'Global',
    'pokemon.regionChinese': 'Chinois',
    'pokemon.regionJapanese': 'Japonais',

    // Card copy sheet (finish/condition editor)
    'cardCopy.title': 'Ma copie',
    'cardCopy.editButton': 'Modifier finition / état',
    'cardCopy.detailsA11yLabel': 'Voir finition et état',
    'cardCopy.notListedHint': 'Non listée pour cette carte',

    // Capture celebration overlay (shared across Pokédex, pinned sets, etc.)
    'capture.rarityCaptured': 'Carte {rarityLabel} capturée',
    'capture.typeComplete': 'Type {type} complet !',
    'capture.milestoneTitle': '{count} Pokémon de type {type} capturés !',
    'capture.dexAdded': 'Nouvelle carte ajoutée au Pokédex !',
    'capture.rarityTitle': '✨ {rarityLabel} !',
    'capture.typeSubtitle': 'Tous les Pokémon de type {type} sont capturés dans ce set',
    'capture.milestoneSubtitle': 'Continue comme ça !',
    'capture.raritySubtitle': 'Une pépite pour ta collection',

    // Shared section tabs (Pokédex / Collection / Wishlist)
    'tabs.pokedex': 'Pokédex national',
    'tabs.collection': 'Collection',
    'tabs.wishlist': 'Wishlist',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.collectionValueLabel': 'Valeur estimée de ta collection : {value}',
    'dashboard.collectionLabel': 'Collection',
    'dashboard.tradesSub': 'échanges',
    'dashboard.tradesLabel': 'Échanges',
    'dashboard.cardsSub': 'cartes',
    'dashboard.ownedLabel': 'Possédées',
    'dashboard.unpinTitle': 'Retirer cet objectif ?',
    'dashboard.unpinMessage': '{name} ne sera plus suivie comme objectif de complétion.',
    'dashboard.typesComplete': '{n}/18 types complets',
    'dashboard.gensComplete': '{n}/9 générations complètes',
    'dashboard.tapForDetail': 'Touche pour voir le détail',
    'dashboard.stateChosen': 'Choisi',
    'dashboard.stateCaptured': 'Capturé',
    'dashboard.stateSeen': 'Vu',
    'dashboard.stateRemaining': 'Restant',
    'dashboard.stateRemainingTitle': 'Restant à voir',
    'dashboard.valueChosen': 'Valeur des cartes choisies',
    'dashboard.valueTotalOwned': 'Valeur totale possédée',
    'dashboard.valueWishlist': 'Valeur théorique de ta wishlist',
    'dashboard.typeBreakdownTitle': 'Type {type}',
    'dashboard.noArtistsYet': 'Aucune carte avec un artiste connu pour l’instant.',
    'dashboard.artistCardCountSingular': '{n} carte',
    'dashboard.artistCardCountPlural': '{n} cartes',
    'dashboard.variantMega': 'Méga-Évolutions',
    'dashboard.variantAlolan': 'Formes d’Alola',
    'dashboard.variantGalarian': 'Formes de Galar',
    'dashboard.variantHisuian': 'Formes d’Hisui',
    'dashboard.variantPaldean': 'Formes de Paldea',
    'dashboard.variantRotom': 'Formes de Rotom',
    'dashboard.variantDeoxys': 'Formes de Deoxys',
    'dashboard.variantGigamax': 'Dynamax / Gigamax',
    'dashboard.badgesLabel': 'Badges',
    'dashboard.vitrineTitle': 'Vitrine',

    // New-set banner
    'newSetBanner.newSet': 'Nouvelle extension : {label}',
    'newSetBanner.view': 'Voir',
    'newSetBanner.moreSingular': '+{n} autre extension récente',
    'newSetBanner.morePlural': '+{n} autres extensions récentes',

    // Set goal picker
    'setGoalPicker.title': 'Objectifs de complétion',
    'setGoalPicker.searchPlaceholder': 'Chercher une extension',
    'setGoalPicker.empty': 'Aucune extension trouvée.',
    'setGoalPicker.cardsCount': '{n} cartes',

    // Stat breakdown modal
    'statBreakdown.owned': 'Possédés',
    'statBreakdown.missing': 'Manquants',

    // Stats tabs modal
    'statsTabs.title': 'Statistiques',
    'statsTabs.progress': 'Progression',
    'statsTabs.generation': 'Génération',
    'statsTabs.type': 'Type',
    'statsTabs.variants': 'Formes',
    'statsTabs.artists': 'Artistes',

    // Badges modals
    'allBadges.title': 'Tous les badges ({n})',
    'badgeDetail.unlocked': 'Débloqué',
    'badgeDetail.locked': 'Verrouillé',
    'badgeDetail.close': 'Fermer',

    // Wishlist
    'wishlist.emptyTitle': 'Aucune carte dans ta wishlist',
    'wishlist.emptyHint': 'Ajoute-en depuis la page détail d’un Pokémon (icône ♥).',
    'wishlist.noResults': 'Aucun résultat avec ces filtres.',
    'wishlist.cardsInWishlistSingular': '{n} carte en wishlist',
    'wishlist.cardsInWishlistPlural': '{n} cartes en wishlist',
    'wishlist.alreadyOwnedSingular': ' · {n} déjà possédée',
    'wishlist.alreadyOwnedPlural': ' · {n} déjà possédées',
    'wishlist.searchPlaceholder': 'Rechercher (nom, set, n°)',
    'wishlist.filtersAndSort': 'Filtres et tri',
    'wishlist.statusAll': 'Toutes',
    'wishlist.statusNotOwned': 'À acheter',
    'wishlist.statusOwned': 'Déjà possédée',
    'wishlist.genChip': 'Gen {n}',
    'wishlist.sortNumAsc': 'N° ↑',
    'wishlist.sortNumDesc': 'N° ↓',
    'wishlist.sortWishedDesc': '♥ récent',
    'wishlist.sortWishedAsc': '♥ ancien',
    'wishlist.sortNameAsc': 'A → Z',
    'wishlist.sortNameDesc': 'Z → A',
    'wishlist.cardsOfTotal': '{owned}/{total} cartes',

    // Favorites / Collection screen
    'favorites.tabBinders': 'Mes binders',
    'favorites.tabArtists': 'Artistes',
    'favorites.tabTrainers': 'Dresseurs',
    'favorites.tabDuplicates': 'Doublons',
    'favorites.tabExtensions': 'Extensions',
    'favorites.regionJapan': '🇯🇵 Japon',
    'favorites.regionChina': '🇨🇳 Chine',
    'favorites.layoutOnePerPage': '1 carte / page',
    'favorites.newBinderPlaceholder': 'Nom du nouveau binder',
    'favorites.noBindersYet': 'Aucun binder pour l’instant — crée-en un ci-dessus.',
    'favorites.binderCardCountSingular': '{n} carte',
    'favorites.binderCardCountPlural': '{n} cartes',
    'favorites.layoutSheetTitle': 'Mise en page',
    'favorites.wizardLayoutTitle': 'Nouveau binder — disposition',
    'favorites.wizardModeTitle': 'Mode de remplissage',
    'favorites.wizardModeFree': 'Libre',
    'favorites.wizardModePrefill': 'Pré-rempli',
    'favorites.wizardModeFreeHint': 'Toutes les pages démarrent vides — ajoute tes cartes une par une.',
    'favorites.wizardModePrefillHint': 'Choisis un set TCG : le binder est généré avec toutes ses cartes, celles que tu ne possèdes pas encore restent marquées comme manquantes.',
    'favorites.wizardSetTitle': 'Choisir un set',
    'favorites.wizardSearchSetPlaceholder': 'Chercher un set',
    'favorites.wizardNext': 'Suivant',
    'favorites.wizardCreate': 'Créer',
    'favorites.searchArtistPlaceholder': 'Chercher un artiste',
    'favorites.noArtistFound': 'Aucun artiste trouvé.',
    'favorites.cardsOfTotal': '{owned}/{total} cartes',
    'favorites.searchCardPlaceholder': 'Chercher une carte',
    'favorites.sortValue': 'Valeur',
    'favorites.sortQuantity': 'Quantité',
    'favorites.sortNameAZ': 'A-Z',
    'favorites.noResults': 'Aucun résultat.',
    'favorites.noDuplicatesYet': 'Aucun doublon pour l’instant — un doublon apparaît ici dès qu’une carte passe à 2 exemplaires ou plus.',
    'favorites.setCardsCount': '{n} cartes',
    'favorites.startPin': 'Commencer',
    'favorites.deleteBinderTitle': 'Supprimer le binder',
    'favorites.deleteConfirmMessage': 'Supprimer "{name}" ?',
    'favorites.a11yViewBinder': 'Voir le binder',
    'favorites.a11yChangeLayout': 'Changer la mise en page',
    'favorites.a11yOrganize': 'Organiser',
    'favorites.organizeHintIdle': 'Choisis un outil, puis touche un emplacement pour l’appliquer.',
    'favorites.organizeHintArmed': 'Touche un emplacement pour appliquer l’outil sélectionné.',
    'favorites.organizeInsertLeft': 'Insérer à gauche',
    'favorites.organizeInsertRight': 'Insérer à droite',
    'favorites.organizeDelete': 'Supprimer',
    'favorites.a11yAddCard': 'Ajouter une carte',
    'favorites.a11yRemoveCard': 'Retirer cette carte',
    'favorites.a11yZoomCard': 'Zoomer sur cette carte',
    'favorites.a11yDeleteTeam': 'Supprimer cette équipe',
    'favorites.a11yClearSlot': 'Retirer ce Pokémon de l’équipe',
    'favorites.a11yAddToSlot': 'Ajouter un Pokémon à l’équipe',

    // App-wide error boundary
    'errorBoundary.title': 'Une erreur est survenue',
    'errorBoundary.message': 'Désolé, quelque chose s’est mal passé. Réessaie, ou reviens plus tard si ça persiste.',
    'errorBoundary.retry': 'Réessayer',

    // Feedback
    'feedback.heroTitle': 'Suggestions & Support',
    'feedback.segmentSuggestions': 'Suggestions',
    'feedback.segmentMine': 'Mes tickets',
    'feedback.segmentAdmin': 'Admin',
    'feedback.noSuggestionsYet': 'Aucune suggestion pour l’instant — sois le premier à en proposer une !',
    'feedback.kindBug': 'Bug',
    'feedback.kindSuggestion': 'Suggestion',
    'feedback.bugPlaceholder': 'Décris le bug que tu as rencontré...',
    'feedback.suggestionPlaceholder': 'Décris ton idée d’amélioration...',
    'feedback.sending': 'Envoi…',
    'feedback.send': 'Envoyer',
    'feedback.noneSentYet': 'Tu n’as encore rien envoyé.',
    'feedback.nothingToReview': 'Rien à traiter.',
    'feedback.replyPlaceholder': 'Répondre…',
    'feedback.addMessagePlaceholder': 'Ajouter un message…',
    'feedback.noRepliesYet': 'Aucune réponse pour l’instant.',

    // Public profile
    'profile.heroTitle': 'Pokédex TCG de {name}',
    'profile.friendStatusFriends': 'Ami',
    'profile.friendStatusPendingSent': 'Demande envoyée',
    'profile.friendStatusAccept': 'Accepter',
    'profile.friendStatusAdd': 'Ajouter',
    'profile.compareButton': 'Comparer avec un autre Pokédex',
    'profile.pinnedSetsTitle': 'Sets en cours',
    'profile.noPinnedSets': 'Aucune extension épinglée pour l’instant.',
    'profile.noWishlistCards': 'Aucune carte dans la wishlist.',
    'profile.proposeTradeButton': 'Proposer un échange',
    'profile.compareSheetTitle': 'Comparer les Pokédex',
    'profile.compareSheetHint': 'Entre le username de l’autre Pokédex (public) à comparer avec celui de {name}.',
    'profile.compareSubmit': 'Comparer',
    'profile.notFoundTitle': 'Ce Pokédex n’existe pas ou est privé',
    'profile.createCta': 'Créer mon Pokédex TCG',

    // Compare A/B
    'compare.bothNotFound': 'Ces deux Pokédex n’existent pas ou sont privés',
    'compare.oneNotFound': 'Le Pokédex "{username}" n’existe pas ou est privé',
    'compare.legendBoth': 'Les deux · {n}',
    'compare.legendOnlyOne': '{name} seul · {n}',
    'compare.legendNeither': 'Aucun · {n}',

    // Trade — shared rich (bold-name) templates + plain shared bits
    'trade.friendProposes': '**{name}** te propose un échange',
    'trade.exchangeWithName': 'Échange avec **{name}**',
    'trade.youGive': 'Tu donnes',
    'trade.youReceive': 'Tu reçois',
    'trade.balancedTrade': 'Échange équilibré',
    'trade.deltaForYou': '{amount} pour toi',
    'trade.proposeButton': 'Proposer l’échange',
    'trade.cancelExchange': 'Annuler l’échange',

    // Trade offer popup
    'tradeOffer.acceptedToast': 'Échange accepté — retrouve-le dans « Échanges en cours » une fois les cartes échangées en vrai.',
    'tradeOffer.declinedToast': 'Offre refusée.',
    'tradeOffer.cancelledToast': 'Offre annulée.',
    'tradeOffer.acceptTitle': 'Accepter l’échange',
    'tradeOffer.acceptMessage': 'Tu donnes {give} et tu reçois {receive}. Une fois les cartes échangées en vrai, vous devrez tous les deux le confirmer pour que ça devienne définitif.',
    'tradeOffer.incomingTitle': 'Proposition de {name}',
    'tradeOffer.outgoingTitle': 'En attente de {name}',
    'tradeOffer.waitingSubtitle': 'Tu attends la réponse de **{name}**',
    'tradeOffer.decline': 'Refuser',
    'tradeOffer.cancelOffer': 'Annuler l’offre',

    // Trade in-progress popup
    'tradeInProgress.title': 'Échange en cours avec {name}',
    'tradeInProgress.subtitle': 'Une fois les cartes échangées en vrai, confirmez tous les deux ici pour finaliser.',
    'tradeInProgress.you': 'Toi',
    'tradeInProgress.waitingForConfirmation': 'En attente de la confirmation de {name}.',
    'tradeInProgress.confirmedButton': 'J’ai échangé la carte',
    'tradeInProgress.cancelConfirmMessage': 'Annuler cet échange avec {name} ? Aucune carte n’a encore changé de main.',
    'tradeInProgress.completedToast': 'Échange finalisé — tu as maintenant {name} !',
    'tradeInProgress.confirmationRecordedToast': 'Confirmation enregistrée — en attente de {name}.',
    'tradeInProgress.cancelledToast': 'Échange annulé.',

    // Trade match popup
    'tradeMatch.headline': 'Échange possible !',
    'tradeMatch.friendWantsThis': '**{name}** recherche cette carte que tu viens de dupliquer.',
    'tradeMatch.later': 'Plus tard',

    // Trade history
    'tradeHistory.title': 'Historique des échanges',
    'tradeHistory.empty': 'Aucun échange finalisé pour l’instant.',

    // Friend card reveal
    'friendReveal.unlockedSubtitle': '{name} a débloqué cette carte',
    'friendReveal.caption': 'N° {cardNumber} · {setName}',
    'friendReveal.bravo': 'Bravo !',

    // QR code modal
    'qrCode.hint': 'Scanne avec l’appareil photo de ton téléphone, ou partage le lien directement.',
    'qrCode.linkCopiedToast': 'Lien copié !',

    // Trade proposal modal
    'tradeProposal.offerTitle': 'Offrir une carte à {name}',
    'tradeProposal.requestTitle': 'Demander en retour',
    'tradeProposal.confirmTitle': 'Confirmer l’échange',
    'tradeProposal.noOwnedCards': 'Tu ne possèdes aucune carte pour l’instant.',
    'tradeProposal.wishlistMatchHint': 'Ces cartes sont dans la wishlist de {name}.',
    'tradeProposal.chooseCardHint': 'Choisis une carte à proposer — les cartes marquées "unique" sont ta seule copie.',
    'tradeProposal.noResultsSearch': 'Aucune carte ne correspond à cette recherche.',
    'tradeProposal.noDuplicatesFromFriend': '{name} n’a aucun doublon à te proposer en retour pour l’instant.',
    'tradeProposal.wishlistStarHint': 'Les cartes marquées ★ sont dans ta wishlist.',
    'tradeProposal.uniqueCopyWarning': 'C’est ta seule copie — tu ne l’auras plus après l’échange.',
    'tradeProposal.tradeSentToast': 'Proposition envoyée à {name} !',
    'tradeProposal.changeRequestedCard': 'Changer la carte demandée',
    'tradeProposal.searchCardPlaceholder': 'Chercher une carte…',

    // Friends screen
    'friends.title': 'Amis',
    'friends.searchPlaceholder': 'Chercher un pseudo pour ajouter un ami',
    'friends.isYou': 'C’est toi',
    'friends.alreadyFriend': 'Déjà ami',
    'friends.noAccountFound': 'Aucun compte avec ce pseudo.',
    'friends.incomingRequests': 'Demandes reçues',
    'friends.outgoingRequests': 'Demandes envoyées',
    'friends.myFriends': 'Mes amis',
    'friends.noFriendsYet': 'Pas encore d’amis — cherche un pseudo ci-dessus pour envoyer une demande.',
    'friends.newsTitle': 'Nouveautés',
    'friends.newsEmpty': 'Rien de notable chez tes amis pour l’instant.',
    'friends.newsEmptyFiltered': 'Rien de notable de ce côté-là pour l’instant.',
    'friends.newsSingle': '**{name}** a obtenu une carte {rarity}',
    'friends.newsGroup': '**{name}** a obtenu {count} cartes remarquables',
    'friends.a11yShareQr': 'Partager mon QR code',
    'friends.a11yRejectRequest': 'Refuser la demande',
    'friends.a11yUnfriend': 'Retirer cet ami',
    'friends.a11yTradeHistory': 'Historique des échanges',
    'friends.unfriendTitle': 'Retirer cet ami',
    'friends.unfriendMessage': 'Retirer "{name}" de tes amis ?',
    'friends.myQrCode': 'Mon QR code',
    'friends.historyTitle': 'Historique',
    'friends.historyEmpty': 'Aucune pêche notable pour l’instant.',

    // Market screen
    'market.title': 'Marché',
    'market.startFreeTradeButton': 'Proposer un échange à un ami',
    'market.chooseFriendTitle': 'Choisir un ami',
    'market.searchFriendPlaceholder': 'Chercher un ami…',
    'market.noFriendsForTrading': 'Ajoute des amis depuis Social pour pouvoir échanger.',
    'market.noFriendMatchesSearch': 'Aucun ami ne correspond à cette recherche.',
    'market.tradesTitle': 'Échanges',
    'market.inProgressTitle': 'Échanges en cours',
    'market.inProgressHint': 'Échangez les cartes en vrai, puis confirmez ici tous les deux.',
    'market.waitingOnYourSide': 'À confirmer de ton côté',
    'market.waitingRow': 'En attente de **{name}**',
    'market.availableTitle': 'Disponible chez tes amis',
    'market.availableHint': 'Doublons de tes amis — propose un échange pour en récupérer un.',
    'market.noAvailableCards': 'Aucun doublon disponible chez tes amis pour l’instant.',
    'market.friendHasDuplicate': '**{name}** a {cardName} en double',
    'market.wantedTitle': 'Recherché par tes amis',
    'market.wantedHint': 'Cartes dans la wishlist de tes amis — propose un échange, doublon ou pas.',
    'market.noWantedCards': 'Tes amis n’ont rien en wishlist pour l’instant.',
    'market.friendWantsCard': '**{name}** recherche {cardName}',
    'market.dontOwnCard': 'Tu ne possèdes pas cette carte',
    'market.onlyCopyWarning': 'Ta seule copie — tu ne l’auras plus après l’échange',

    // Binder slot picker (card or photo)
    'binderPicker.photoPermToast': 'Autorise l’accès à tes photos pour importer une image.',
    'binderPicker.photoImportErrToast': 'Impossible d’importer cette photo, réessaie.',
    'binderPicker.chooseCardTitle': 'Choisir une carte',
    'binderPicker.importPhotoTitle': 'Importer une photo',
    'binderPicker.modeCard': 'Carte',
    'binderPicker.modePhoto': 'Photo',
    'binderPicker.photoHint': 'Importe une photo perso pour cet emplacement — elle sera recadrée au format d’une carte.',
    'binderPicker.importing': 'Import…',
    'binderPicker.choosePhoto': 'Choisir une photo',
    'binderPicker.searchPlaceholder': 'Chercher un Pokémon (nom ou n°)',
    'binderPicker.typeToSearch': 'Tape un nom ou un numéro pour chercher.',
    'binderPicker.noCardsForPokemon': 'Aucune carte TCG connue pour ce Pokémon.',

    // Trainers panel
    'trainers.countSingular': '{n} dresseur',
    'trainers.countPlural': '{n} dresseurs',
    'trainers.searchPlaceholder': 'Chercher un dresseur',
    'trainers.notFound': 'Aucun dresseur trouvé.',
    'trainers.a11yGridView': 'Vue grille',
    'trainers.a11yListView': 'Vue liste',
  },
  en: {
    'common.back': 'Back',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.save': 'Save',
    'common.copy': 'Copy',
    'common.error': 'Error',
    'common.copied': 'Copied',
    'common.cancel': 'Cancel',
    'common.choose': 'Choose',
    'common.all': 'All',
    'common.clear': 'Clear',
    'common.delete': 'Delete',
    'common.unpin': 'Unpin',
    'common.close': 'Close',
    'common.refresh': 'Refresh',
    'common.loadError': 'Couldn’t load your profile, try again.',

    // App layout — global FABs
    'appLayout.a11ySettings': 'Settings',
    'appLayout.a11yMarket': 'Market',
    'appLayout.a11yInProgressTrade': 'Trade in progress',

    'auth.login.title': 'Log in',
    'auth.login.submit': 'Log in',
    'auth.login.forgotPassword': 'Forgot password?',
    'auth.login.noAccount': 'No account? Sign up',
    'auth.login.genericErr': 'Login failed',

    'auth.signup.title': 'Create an account',
    'auth.signup.passwordPlaceholder': 'Password (min 6)',
    'auth.signup.usernamePlaceholder': 'Username (immutable, e.g. tristan-42)',
    'auth.signup.checking': 'Checking…',
    'auth.signup.available': 'Available ✓',
    'auth.signup.taken': 'Already taken',
    'auth.signup.invalidFormat': 'Invalid format',
    'auth.signup.displayNamePlaceholder': 'Display name (public)',
    'auth.signup.submit': 'Sign up',
    'auth.signup.haveAccount': 'Already have an account? Log in',
    'auth.signup.legalPrefix': 'By signing up, you accept the',
    'auth.signup.legalTerms': 'Terms',
    'auth.signup.legalAnd': 'and the',
    'auth.signup.legalPrivacy': 'privacy policy',
    'auth.signup.usernameInvalidMsg': 'Invalid username (3–30 characters, a-z 0-9 _ - only, must start with a-z or 0-9)',
    'auth.signup.usernameTakenErr': 'This username is already taken',
    'auth.signup.genericErr': 'Sign up failed',
    'auth.signup.checkEmailTitle': 'Check your inbox',
    'auth.signup.checkEmailBody': 'We sent a confirmation link to {email}. Click it to activate your account, then log in.',
    'auth.signup.backToLogin': 'Back to login',

    'settings.usernameLabel': 'Username (immutable)',
    'settings.displayNameLabel': 'Display name',
    'settings.publicProfileLabel': 'Public profile',
    'settings.darkThemeLabel': 'Dark theme',
    'settings.languageLabel': 'Language',
    'settings.paletteLabel': 'Color palette',
    'settings.animationsLabel': 'Animations',
    'settings.shareLinkLabel': 'Share link',
    'settings.feedbackAdminLabel': 'Suggestions & tickets (admin)',
    'settings.feedbackLabel': 'Suggestions & bugs',
    'settings.logout': 'Log out',
    'settings.terms': 'Terms of use',
    'settings.privacy': 'Privacy',
    'settings.trainerFallback': 'Trainer',
    'settings.displayNameEmpty': 'Display name can’t be empty.',

    'pokedex.heroTitle': 'National Pokédex',
    'pokedex.filterHint': 'Filter: {hint}',

    'search.placeholder': 'Search (name or #)',
    'search.owned': 'Owned',
    'search.missing': 'Missing',
    'search.filtersTitle': 'Filters',
    'search.statusLabel': 'Status',
    'search.sectionLabel': 'Generation / Type / Set / Rarity',
    'search.sortLabel': 'Sort',
    'search.resetFilters': 'Reset filters',
    'search.typeLabel': 'Type',
    'search.setLabel': 'Set',
    'search.setTcgTitle': 'TCG Set',
    'search.rarityLabel': 'Rarity',
    'search.generationLabel': 'Generation',
    'search.typeChip': 'Type: {value}',
    'search.typeChipCount': 'Type ({n})',
    'search.setChip': 'Set: {value}',
    'search.rarityChip': 'Rarity: {value}',
    'search.genChipCount': 'Generation ({n})',
    'search.a11yClear': 'Clear search',
    'search.a11yToggleSearch': 'Search',
    'search.a11yToggleFilter': 'Filter',
    'search.a11yCycleColumns': 'Change column count',
    'search.a11yTogglePrice': 'Show prices',

    'cardFilter.title': 'Filter by set',
    'cardFilter.selectedSingular': '{n} set selected',
    'cardFilter.selectedPlural': '{n} sets selected',
    'cardFilter.otherSeries': 'Other',
    'cardFilter.a11yJumpToSet': 'Jump to this set',

    'pokemon.a11yFavorite': 'Add to favorites',
    'pokemon.a11yUnfavorite': 'Remove from favorites',
    'pokemon.a11yShowcase': 'Add to showcase',
    'pokemon.a11yUnshowcase': 'Remove from showcase',
    'pokemon.a11yPrev': 'Previous Pokémon',
    'pokemon.a11yNext': 'Next Pokémon',
    'pokemon.notFound': 'Unknown Pokémon',
    'pokemon.showcaseLimitToast': 'Showcase limited to {n} cards — remove one before adding another.',
    'pokemon.noCardsKnown': 'No known TCG card for this Pokémon in the database.',
    'pokemon.noRegionCards': 'No {region} card known for this Pokémon.',
    'pokemon.noCardsInSelectedSets': 'No card in the selected sets.',
    'pokemon.wishFilterActive': '♥ Wishlist filter active — tap to see all',
    'pokemon.infoBanner': 'Owned cards appear unlocked. Tap a card to make it your National Pokédex card.',
    'pokemon.chooseCardTitle': 'Choose this card',
    'pokemon.chooseCardMessage': 'Make "{cardName}" your National Pokédex card for {pokemonName}?',
    'pokemon.addedOn': 'Added on {date}',
    'pokemon.regionGlobal': 'Global',
    'pokemon.regionChinese': 'Chinese',
    'pokemon.regionJapanese': 'Japanese',

    'cardCopy.title': 'My copy',
    'cardCopy.editButton': 'Edit finish / condition',
    'cardCopy.detailsA11yLabel': 'View finish and condition',
    'cardCopy.notListedHint': 'Not listed for this card',

    'capture.rarityCaptured': '{rarityLabel} card captured',
    'capture.typeComplete': '{type} type complete!',
    'capture.milestoneTitle': '{count} {type}-type Pokémon captured!',
    'capture.dexAdded': 'New card added to the Pokédex!',
    'capture.rarityTitle': '✨ {rarityLabel}!',
    'capture.typeSubtitle': 'All {type}-type Pokémon are captured in this set',
    'capture.milestoneSubtitle': 'Keep it up!',
    'capture.raritySubtitle': 'A gem for your collection',

    'tabs.pokedex': 'National Pokédex',
    'tabs.collection': 'Collection',
    'tabs.wishlist': 'Wishlist',

    'dashboard.title': 'Dashboard',
    'dashboard.collectionValueLabel': 'Estimated value of your collection: {value}',
    'dashboard.collectionLabel': 'Collection',
    'dashboard.tradesSub': 'trades',
    'dashboard.tradesLabel': 'Trades',
    'dashboard.cardsSub': 'cards',
    'dashboard.ownedLabel': 'Owned',
    'dashboard.unpinTitle': 'Remove this goal?',
    'dashboard.unpinMessage': '{name} will no longer be tracked as a completion goal.',
    'dashboard.typesComplete': '{n}/18 types complete',
    'dashboard.gensComplete': '{n}/9 generations complete',
    'dashboard.tapForDetail': 'Tap to see the detail',
    'dashboard.stateChosen': 'Chosen',
    'dashboard.stateCaptured': 'Captured',
    'dashboard.stateSeen': 'Seen',
    'dashboard.stateRemaining': 'Remaining',
    'dashboard.stateRemainingTitle': 'Remaining to see',
    'dashboard.valueChosen': 'Value of chosen cards',
    'dashboard.valueTotalOwned': 'Total owned value',
    'dashboard.valueWishlist': 'Theoretical value of your wishlist',
    'dashboard.typeBreakdownTitle': '{type} type',
    'dashboard.noArtistsYet': 'No card with a known artist yet.',
    'dashboard.artistCardCountSingular': '{n} card',
    'dashboard.artistCardCountPlural': '{n} cards',
    'dashboard.variantMega': 'Mega Evolutions',
    'dashboard.variantAlolan': 'Alolan Forms',
    'dashboard.variantGalarian': 'Galarian Forms',
    'dashboard.variantHisuian': 'Hisuian Forms',
    'dashboard.variantPaldean': 'Paldean Forms',
    'dashboard.variantRotom': 'Rotom Forms',
    'dashboard.variantDeoxys': 'Deoxys Forms',
    'dashboard.variantGigamax': 'Dynamax / Gigamax',
    'dashboard.badgesLabel': 'Badges',
    'dashboard.vitrineTitle': 'Showcase',

    'newSetBanner.newSet': 'New set: {label}',
    'newSetBanner.view': 'View',
    'newSetBanner.moreSingular': '+{n} more recent set',
    'newSetBanner.morePlural': '+{n} more recent sets',

    'setGoalPicker.title': 'Completion goals',
    'setGoalPicker.searchPlaceholder': 'Search a set',
    'setGoalPicker.empty': 'No set found.',
    'setGoalPicker.cardsCount': '{n} cards',

    'statBreakdown.owned': 'Owned',
    'statBreakdown.missing': 'Missing',

    'statsTabs.title': 'Statistics',
    'statsTabs.progress': 'Progress',
    'statsTabs.generation': 'Generation',
    'statsTabs.type': 'Type',
    'statsTabs.variants': 'Forms',
    'statsTabs.artists': 'Artists',

    'allBadges.title': 'All badges ({n})',
    'badgeDetail.unlocked': 'Unlocked',
    'badgeDetail.locked': 'Locked',
    'badgeDetail.close': 'Close',

    'wishlist.emptyTitle': 'No card in your wishlist',
    'wishlist.emptyHint': 'Add some from a Pokémon detail page (♥ icon).',
    'wishlist.noResults': 'No result with these filters.',
    'wishlist.cardsInWishlistSingular': '{n} card in wishlist',
    'wishlist.cardsInWishlistPlural': '{n} cards in wishlist',
    'wishlist.alreadyOwnedSingular': ' · {n} already owned',
    'wishlist.alreadyOwnedPlural': ' · {n} already owned',
    'wishlist.searchPlaceholder': 'Search (name, set, #)',
    'wishlist.filtersAndSort': 'Filters & sort',
    'wishlist.statusAll': 'All',
    'wishlist.statusNotOwned': 'To buy',
    'wishlist.statusOwned': 'Already owned',
    'wishlist.genChip': 'Gen {n}',
    'wishlist.sortNumAsc': 'N° ↑',
    'wishlist.sortNumDesc': 'N° ↓',
    'wishlist.sortWishedDesc': '♥ recent',
    'wishlist.sortWishedAsc': '♥ oldest',
    'wishlist.sortNameAsc': 'A → Z',
    'wishlist.sortNameDesc': 'Z → A',
    'wishlist.cardsOfTotal': '{owned}/{total} cards',

    'favorites.tabBinders': 'My binders',
    'favorites.tabArtists': 'Artists',
    'favorites.tabTrainers': 'Trainers',
    'favorites.tabDuplicates': 'Duplicates',
    'favorites.tabExtensions': 'Sets',
    'favorites.regionJapan': '🇯🇵 Japan',
    'favorites.regionChina': '🇨🇳 China',
    'favorites.layoutOnePerPage': '1 card / page',
    'favorites.newBinderPlaceholder': 'New binder name',
    'favorites.noBindersYet': 'No binder yet — create one above.',
    'favorites.binderCardCountSingular': '{n} card',
    'favorites.binderCardCountPlural': '{n} cards',
    'favorites.layoutSheetTitle': 'Layout',
    'favorites.wizardLayoutTitle': 'New binder — layout',
    'favorites.wizardModeTitle': 'Fill mode',
    'favorites.wizardModeFree': 'Free',
    'favorites.wizardModePrefill': 'Prefilled',
    'favorites.wizardModeFreeHint': 'Every page starts empty — add your cards one at a time.',
    'favorites.wizardModePrefillHint': 'Pick a TCG set: the binder is generated with every card in it, and any you don’t own yet stay marked as missing.',
    'favorites.wizardSetTitle': 'Pick a set',
    'favorites.wizardSearchSetPlaceholder': 'Search a set',
    'favorites.wizardNext': 'Next',
    'favorites.wizardCreate': 'Create',
    'favorites.searchArtistPlaceholder': 'Search an artist',
    'favorites.noArtistFound': 'No artist found.',
    'favorites.cardsOfTotal': '{owned}/{total} cards',
    'favorites.searchCardPlaceholder': 'Search a card',
    'favorites.sortValue': 'Value',
    'favorites.sortQuantity': 'Quantity',
    'favorites.sortNameAZ': 'A-Z',
    'favorites.noResults': 'No result.',
    'favorites.noDuplicatesYet': 'No duplicate yet — one appears here as soon as a card reaches 2 or more copies.',
    'favorites.setCardsCount': '{n} cards',
    'favorites.startPin': 'Start',
    'favorites.deleteBinderTitle': 'Delete binder',
    'favorites.deleteConfirmMessage': 'Delete "{name}"?',
    'favorites.a11yViewBinder': 'View binder',
    'favorites.a11yChangeLayout': 'Change layout',
    'favorites.a11yOrganize': 'Organize',
    'favorites.organizeHintIdle': 'Pick a tool, then tap a slot to apply it.',
    'favorites.organizeHintArmed': 'Tap a slot to apply the selected tool.',
    'favorites.organizeInsertLeft': 'Insert left',
    'favorites.organizeInsertRight': 'Insert right',
    'favorites.organizeDelete': 'Delete',
    'favorites.a11yAddCard': 'Add a card',
    'favorites.a11yRemoveCard': 'Remove this card',
    'favorites.a11yZoomCard': 'Zoom on this card',
    'favorites.a11yDeleteTeam': 'Delete this team',
    'favorites.a11yClearSlot': 'Remove this Pokémon from the team',
    'favorites.a11yAddToSlot': 'Add a Pokémon to the team',

    'errorBoundary.title': 'Something went wrong',
    'errorBoundary.message': 'Sorry about that. Try again, or come back later if it keeps happening.',
    'errorBoundary.retry': 'Try again',

    'feedback.heroTitle': 'Suggestions & Support',
    'feedback.segmentSuggestions': 'Suggestions',
    'feedback.segmentMine': 'My tickets',
    'feedback.segmentAdmin': 'Admin',
    'feedback.noSuggestionsYet': 'No suggestion yet — be the first to propose one!',
    'feedback.kindBug': 'Bug',
    'feedback.kindSuggestion': 'Suggestion',
    'feedback.bugPlaceholder': 'Describe the bug you ran into...',
    'feedback.suggestionPlaceholder': 'Describe your improvement idea...',
    'feedback.sending': 'Sending…',
    'feedback.send': 'Send',
    'feedback.noneSentYet': 'You haven’t sent anything yet.',
    'feedback.nothingToReview': 'Nothing to review.',
    'feedback.replyPlaceholder': 'Reply…',
    'feedback.addMessagePlaceholder': 'Add a message…',
    'feedback.noRepliesYet': 'No reply yet.',

    'profile.heroTitle': '{name}’s TCG Pokédex',
    'profile.friendStatusFriends': 'Friend',
    'profile.friendStatusPendingSent': 'Request sent',
    'profile.friendStatusAccept': 'Accept',
    'profile.friendStatusAdd': 'Add',
    'profile.compareButton': 'Compare with another Pokédex',
    'profile.pinnedSetsTitle': 'Sets in progress',
    'profile.noPinnedSets': 'No pinned set yet.',
    'profile.noWishlistCards': 'No card in the wishlist.',
    'profile.proposeTradeButton': 'Propose a trade',
    'profile.compareSheetTitle': 'Compare Pokédexes',
    'profile.compareSheetHint': 'Enter the username of the other (public) Pokédex to compare with {name}’s.',
    'profile.compareSubmit': 'Compare',
    'profile.notFoundTitle': 'This Pokédex doesn’t exist or is private',
    'profile.createCta': 'Create my TCG Pokédex',

    'compare.bothNotFound': 'Neither of these Pokédexes exist or are private',
    'compare.oneNotFound': 'The "{username}" Pokédex doesn’t exist or is private',
    'compare.legendBoth': 'Both · {n}',
    'compare.legendOnlyOne': 'Only {name} · {n}',
    'compare.legendNeither': 'Neither · {n}',

    'trade.friendProposes': '**{name}** offers you a trade',
    'trade.exchangeWithName': 'Trade with **{name}**',
    'trade.youGive': 'You give',
    'trade.youReceive': 'You receive',
    'trade.balancedTrade': 'Balanced trade',
    'trade.deltaForYou': '{amount} for you',
    'trade.proposeButton': 'Propose the trade',
    'trade.cancelExchange': 'Cancel the trade',

    'tradeOffer.acceptedToast': 'Trade accepted — find it in "Trades in progress" once the cards are exchanged for real.',
    'tradeOffer.declinedToast': 'Offer declined.',
    'tradeOffer.cancelledToast': 'Offer cancelled.',
    'tradeOffer.acceptTitle': 'Accept the trade',
    'tradeOffer.acceptMessage': 'You give {give} and receive {receive}. Once the cards are exchanged for real, you’ll both need to confirm it to make it final.',
    'tradeOffer.incomingTitle': '{name}’s offer',
    'tradeOffer.outgoingTitle': 'Waiting on {name}',
    'tradeOffer.waitingSubtitle': 'Waiting for **{name}**’s response',
    'tradeOffer.decline': 'Decline',
    'tradeOffer.cancelOffer': 'Cancel the offer',

    'tradeInProgress.title': 'Trade in progress with {name}',
    'tradeInProgress.subtitle': 'Once the cards are exchanged for real, both confirm here to finalize.',
    'tradeInProgress.you': 'You',
    'tradeInProgress.waitingForConfirmation': 'Waiting for {name}’s confirmation.',
    'tradeInProgress.confirmedButton': 'I’ve traded the card',
    'tradeInProgress.cancelConfirmMessage': 'Cancel this trade with {name}? No card has changed hands yet.',
    'tradeInProgress.completedToast': 'Trade complete — you now have {name}!',
    'tradeInProgress.confirmationRecordedToast': 'Confirmation recorded — waiting on {name}.',
    'tradeInProgress.cancelledToast': 'Trade cancelled.',

    'tradeMatch.headline': 'Trade possible!',
    'tradeMatch.friendWantsThis': '**{name}** wants this card you just duplicated.',
    'tradeMatch.later': 'Later',

    'tradeHistory.title': 'Trade history',
    'tradeHistory.empty': 'No completed trade yet.',

    'friendReveal.unlockedSubtitle': '{name} unlocked this card',
    'friendReveal.caption': 'No. {cardNumber} · {setName}',
    'friendReveal.bravo': 'Nice!',

    'qrCode.hint': 'Scan with your phone’s camera, or share the link directly.',
    'qrCode.linkCopiedToast': 'Link copied!',

    'tradeProposal.offerTitle': 'Offer a card to {name}',
    'tradeProposal.requestTitle': 'Request in return',
    'tradeProposal.confirmTitle': 'Confirm the trade',
    'tradeProposal.noOwnedCards': 'You don’t own any card yet.',
    'tradeProposal.wishlistMatchHint': 'These cards are on {name}’s wishlist.',
    'tradeProposal.chooseCardHint': 'Choose a card to offer — cards marked "unique" are your only copy.',
    'tradeProposal.noResultsSearch': 'No card matches this search.',
    'tradeProposal.noDuplicatesFromFriend': '{name} has no duplicate to offer back yet.',
    'tradeProposal.wishlistStarHint': 'Cards marked ★ are on your wishlist.',
    'tradeProposal.uniqueCopyWarning': 'This is your only copy — you won’t have it anymore after the trade.',
    'tradeProposal.tradeSentToast': 'Offer sent to {name}!',
    'tradeProposal.changeRequestedCard': 'Change the requested card',
    'tradeProposal.searchCardPlaceholder': 'Search a card…',

    'friends.title': 'Friends',
    'friends.searchPlaceholder': 'Search a username to add a friend',
    'friends.isYou': 'That’s you',
    'friends.alreadyFriend': 'Already friends',
    'friends.noAccountFound': 'No account with this username.',
    'friends.incomingRequests': 'Received requests',
    'friends.outgoingRequests': 'Sent requests',
    'friends.myFriends': 'My friends',
    'friends.noFriendsYet': 'No friends yet — search a username above to send a request.',
    'friends.newsTitle': 'News',
    'friends.newsEmpty': 'Nothing notable from your friends yet.',
    'friends.newsEmptyFiltered': 'Nothing notable on that side yet.',
    'friends.newsSingle': '**{name}** got a {rarity} card',
    'friends.newsGroup': '**{name}** got {count} notable cards',
    'friends.a11yShareQr': 'Share my QR code',
    'friends.a11yRejectRequest': 'Reject request',
    'friends.a11yUnfriend': 'Remove this friend',
    'friends.a11yTradeHistory': 'Trade history',
    'friends.unfriendTitle': 'Remove this friend',
    'friends.unfriendMessage': 'Remove "{name}" from your friends?',
    'friends.myQrCode': 'My QR code',
    'friends.historyTitle': 'History',
    'friends.historyEmpty': 'No notable pull yet.',

    'market.title': 'Market',
    'market.startFreeTradeButton': 'Propose a trade to a friend',
    'market.chooseFriendTitle': 'Choose a friend',
    'market.searchFriendPlaceholder': 'Search a friend…',
    'market.noFriendsForTrading': 'Add friends from Social to be able to trade.',
    'market.noFriendMatchesSearch': 'No friend matches this search.',
    'market.tradesTitle': 'Trades',
    'market.inProgressTitle': 'Trades in progress',
    'market.inProgressHint': 'Trade the cards for real, then both confirm here.',
    'market.waitingOnYourSide': 'Waiting on your confirmation',
    'market.waitingRow': 'Waiting on **{name}**',
    'market.availableTitle': 'Available from your friends',
    'market.availableHint': 'Your friends’ duplicates — propose a trade to get one.',
    'market.noAvailableCards': 'No duplicate available from your friends yet.',
    'market.friendHasDuplicate': '**{name}** has {cardName} as a duplicate',
    'market.wantedTitle': 'Wanted by your friends',
    'market.wantedHint': 'Cards on your friends’ wishlist — propose a trade, duplicate or not.',
    'market.noWantedCards': 'Your friends have nothing on their wishlist yet.',
    'market.friendWantsCard': '**{name}** wants {cardName}',
    'market.dontOwnCard': 'You don’t own this card',
    'market.onlyCopyWarning': 'Your only copy — you won’t have it anymore after the trade',

    'binderPicker.photoPermToast': 'Allow access to your photos to import an image.',
    'binderPicker.photoImportErrToast': 'Couldn’t import this photo, try again.',
    'binderPicker.chooseCardTitle': 'Choose a card',
    'binderPicker.importPhotoTitle': 'Import a photo',
    'binderPicker.modeCard': 'Card',
    'binderPicker.modePhoto': 'Photo',
    'binderPicker.photoHint': 'Import a personal photo for this slot — it’ll be cropped to a card’s shape.',
    'binderPicker.importing': 'Importing…',
    'binderPicker.choosePhoto': 'Choose a photo',
    'binderPicker.searchPlaceholder': 'Search a Pokémon (name or #)',
    'binderPicker.typeToSearch': 'Type a name or number to search.',
    'binderPicker.noCardsForPokemon': 'No known TCG card for this Pokémon.',

    'trainers.countSingular': '{n} trainer',
    'trainers.countPlural': '{n} trainers',
    'trainers.searchPlaceholder': 'Search a trainer',
    'trainers.notFound': 'No trainer found.',
    'trainers.a11yGridView': 'Grid view',
    'trainers.a11yListView': 'List view',
  },
} as const;

export type StringKey = keyof typeof STRINGS['fr'];
