// Flat FR/EN dictionary for the app's UI text. Only covers the screens/components
// translated so far (auth, Pokédex browsing, Pokémon detail, Settings) — see the
// language-toggle plan doc for what's still French-only regardless of locale.
// Extend this file (add keys to both `fr` and `en`) as more screens get translated;
// no architecture change needed for that.
export const STRINGS = {
  fr: {
    // Common
    'common.back': 'Retour',
    'common.email': 'Email',
    'common.password': 'Mot de passe',
    'common.save': 'Enregistrer',
    'common.copy': 'Copier',
    'common.error': 'Erreur',
    'common.copied': 'Copié',
    'common.cancel': 'Annuler',
    'common.choose': 'Choisir',
    'common.all': 'Tous',
    'common.clear': 'Effacer',
    'common.delete': 'Supprimer',
    'common.unpin': 'Désépingler',

    // Auth — login
    'auth.login.title': 'Connexion',
    'auth.login.submit': 'Se connecter',
    'auth.login.forgotPassword': 'Mot de passe oublié ?',
    'auth.login.noAccount': "Pas de compte ? S'inscrire",
    'auth.login.genericErr': 'Échec de la connexion',

    // Auth — signup
    'auth.signup.title': 'Créer un compte',
    'auth.signup.passwordPlaceholder': 'Mot de passe (min 6)',
    'auth.signup.usernamePlaceholder': 'Username (immutable, ex: tristan-42)',
    'auth.signup.checking': 'Vérification…',
    'auth.signup.available': 'Disponible ✓',
    'auth.signup.taken': 'Déjà pris',
    'auth.signup.invalidFormat': 'Format invalide',
    'auth.signup.displayNamePlaceholder': 'Nom affiché (public)',
    'auth.signup.submit': "S'inscrire",
    'auth.signup.haveAccount': 'Déjà un compte ? Se connecter',
    'auth.signup.legalPrefix': "En t'inscrivant, tu acceptes les",
    'auth.signup.legalTerms': 'CGU',
    'auth.signup.legalAnd': 'et la',
    'auth.signup.legalPrivacy': 'politique de confidentialité',
    'auth.signup.usernameInvalidMsg': 'Username invalide (3–30 caractères, a-z 0-9 _ - uniquement, doit commencer par a-z ou 0-9)',
    'auth.signup.usernameTakenErr': 'Ce username est déjà pris',
    'auth.signup.genericErr': 'Inscription échouée',
    'auth.signup.checkEmailTitle': 'Vérifie ta boîte mail',
    'auth.signup.checkEmailBody': 'On a envoyé un lien de confirmation à {email}. Clique dessus pour activer ton compte, puis connecte-toi.',
    'auth.signup.backToLogin': 'Retour à la connexion',

    // Settings
    'settings.usernameLabel': 'Username (immuable)',
    'settings.displayNameLabel': 'Nom affiché',
    'settings.publicProfileLabel': 'Profil public',
    'settings.darkThemeLabel': 'Thème sombre',
    'settings.languageLabel': 'Langue',
    'settings.paletteLabel': 'Palette de couleurs',
    'settings.animationsLabel': 'Animations',
    'settings.shareLinkLabel': 'Lien de partage',
    'settings.feedbackAdminLabel': 'Suggestions & tickets (admin)',
    'settings.feedbackLabel': 'Suggestions & bugs',
    'settings.logout': 'Se déconnecter',
    'settings.terms': "Conditions d'utilisation",
    'settings.privacy': 'Confidentialité',
    'settings.trainerFallback': 'Dresseur',

    // Pokédex screen
    'pokedex.heroTitle': 'Pokédex National',
    'pokedex.filterHint': 'Filtre : {hint}',

    // Search / filter bar
    'search.placeholder': 'Rechercher (nom ou n°)',
    'search.owned': 'Possédés',
    'search.missing': 'Manquants',
    'search.filtersTitle': 'Filtres',
    'search.statusLabel': 'Statut',
    'search.sectionLabel': 'Génération / Type / Set / Rareté',
    'search.sortLabel': 'Tri',
    'search.resetFilters': 'Réinitialiser les filtres',
    'search.typeLabel': 'Type',
    'search.setLabel': 'Set',
    'search.setTcgTitle': 'Set TCG',
    'search.rarityLabel': 'Rareté',
    'search.generationLabel': 'Génération',
    'search.typeChip': 'Type: {value}',
    'search.typeChipCount': 'Type ({n})',
    'search.setChip': 'Set: {value}',
    'search.rarityChip': 'Rareté: {value}',
    'search.genChipCount': 'Génération ({n})',

    // Card filter tree (extension filter)
    'cardFilter.title': 'Filtrer par extension',
    'cardFilter.selectedSingular': '{n} set sélectionné',
    'cardFilter.selectedPlural': '{n} sets sélectionnés',
    'cardFilter.otherSeries': 'Autres',

    // Pokémon detail
    'pokemon.notFound': 'Pokémon inconnu',
    'pokemon.showcaseLimitToast': 'Vitrine limitée à {n} cartes — retire-en une avant d’en ajouter une autre.',
    'pokemon.noCardsKnown': 'Aucune carte TCG connue pour ce Pokémon dans la base.',
    'pokemon.noRegionCards': 'Aucune carte {region} connue pour ce Pokémon.',
    'pokemon.noCardsInSelectedSets': 'Aucune carte dans les extensions sélectionnées.',
    'pokemon.wishFilterActive': '♥ Filtre wish actif — tap pour tout voir',
    'pokemon.infoBanner': 'Les cartes possédées apparaissent déverrouillées. Touche une carte pour en faire ta carte choisie du Pokédex national.',
    'pokemon.chooseCardTitle': 'Choisir cette carte',
    'pokemon.chooseCardMessage': 'Faire de « {cardName} » ta carte choisie du Pokédex national pour {pokemonName} ?',
    'pokemon.addedOn': 'Ajoutée le {date}',
    'pokemon.regionGlobal': 'Global',
    'pokemon.regionChinese': 'Chinois',
    'pokemon.regionJapanese': 'Japonais',

    // Card copy sheet (finish/condition editor)
    'cardCopy.title': 'Ma copie',
    'cardCopy.editButton': 'Modifier finition / état',
    'cardCopy.detailsA11yLabel': 'Voir finition et état',
    'cardCopy.notListedHint': 'Non listée pour cette carte',

    // Capture celebration overlay (shared across Pokédex, pinned sets, etc.)
    'capture.rarityCaptured': 'Carte {rarityLabel} capturée',
    'capture.typeComplete': 'Type {type} complet !',
    'capture.milestoneTitle': '{count} Pokémon de type {type} capturés !',
    'capture.dexAdded': 'Nouvelle carte ajoutée au Pokédex !',
    'capture.rarityTitle': '✨ {rarityLabel} !',
    'capture.typeSubtitle': 'Tous les Pokémon de type {type} sont capturés dans ce set',
    'capture.milestoneSubtitle': 'Continue comme ça !',
    'capture.raritySubtitle': 'Une pépite pour ta collection',

    // Shared section tabs (Pokédex / Collection / Wishlist)
    'tabs.pokedex': 'Pokédex national',
    'tabs.collection': 'Collection',
    'tabs.wishlist': 'Wishlist',

    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.collectionValueLabel': 'Valeur estimée de ta collection : {value}',
    'dashboard.collectionLabel': 'Collection',
    'dashboard.tradesSub': 'échanges',
    'dashboard.tradesLabel': 'Échanges',
    'dashboard.cardsSub': 'cartes',
    'dashboard.ownedLabel': 'Possédées',
    'dashboard.unpinTitle': 'Retirer cet objectif ?',
    'dashboard.unpinMessage': '{name} ne sera plus suivie comme objectif de complétion.',
    'dashboard.typesComplete': '{n}/18 types complets',
    'dashboard.gensComplete': '{n}/9 générations complètes',
    'dashboard.tapForDetail': 'Touche pour voir le détail',
    'dashboard.stateChosen': 'Choisi',
    'dashboard.stateCaptured': 'Capturé',
    'dashboard.stateSeen': 'Vu',
    'dashboard.stateRemaining': 'Restant',
    'dashboard.stateRemainingTitle': 'Restant à voir',
    'dashboard.valueChosen': 'Valeur des cartes choisies',
    'dashboard.valueTotalOwned': 'Valeur totale possédée',
    'dashboard.valueWishlist': 'Valeur théorique de ta wishlist',
    'dashboard.typeBreakdownTitle': 'Type {type}',
    'dashboard.noArtistsYet': 'Aucune carte avec un artiste connu pour l’instant.',
    'dashboard.artistCardCountSingular': '{n} carte',
    'dashboard.artistCardCountPlural': '{n} cartes',
    'dashboard.variantMega': 'Méga-Évolutions',
    'dashboard.variantAlolan': 'Formes d’Alola',
    'dashboard.variantGalarian': 'Formes de Galar',
    'dashboard.variantHisuian': 'Formes d’Hisui',
    'dashboard.variantPaldean': 'Formes de Paldea',
    'dashboard.variantRotom': 'Formes de Rotom',
    'dashboard.variantDeoxys': 'Formes de Deoxys',
    'dashboard.variantGigamax': 'Dynamax / Gigamax',
    'dashboard.badgesLabel': 'Badges',
    'dashboard.vitrineTitle': 'Vitrine',

    // New-set banner
    'newSetBanner.newSet': 'Nouvelle extension : {label}',
    'newSetBanner.view': 'Voir',
    'newSetBanner.moreSingular': '+{n} autre extension récente',
    'newSetBanner.morePlural': '+{n} autres extensions récentes',

    // Set goal picker
    'setGoalPicker.title': 'Objectifs de complétion',
    'setGoalPicker.searchPlaceholder': 'Chercher une extension',
    'setGoalPicker.empty': 'Aucune extension trouvée.',
    'setGoalPicker.cardsCount': '{n} cartes',

    // Stat breakdown modal
    'statBreakdown.owned': 'Possédés',
    'statBreakdown.missing': 'Manquants',

    // Stats tabs modal
    'statsTabs.title': 'Statistiques',
    'statsTabs.progress': 'Progression',
    'statsTabs.generation': 'Génération',
    'statsTabs.type': 'Type',
    'statsTabs.variants': 'Formes',
    'statsTabs.artists': 'Artistes',

    // Badges modals
    'allBadges.title': 'Tous les badges ({n})',
    'badgeDetail.unlocked': 'Débloqué',
    'badgeDetail.locked': 'Verrouillé',
    'badgeDetail.close': 'Fermer',

    // Wishlist
    'wishlist.emptyTitle': 'Aucune carte dans ta wishlist',
    'wishlist.emptyHint': 'Ajoute-en depuis la page détail d’un Pokémon (icône ♥).',
    'wishlist.noResults': 'Aucun résultat avec ces filtres.',
    'wishlist.cardsInWishlistSingular': '{n} carte en wishlist',
    'wishlist.cardsInWishlistPlural': '{n} cartes en wishlist',
    'wishlist.alreadyOwnedSingular': ' · {n} déjà possédée',
    'wishlist.alreadyOwnedPlural': ' · {n} déjà possédées',
    'wishlist.searchPlaceholder': 'Rechercher (nom, set, n°)',
    'wishlist.filtersAndSort': 'Filtres et tri',
    'wishlist.statusAll': 'Toutes',
    'wishlist.statusNotOwned': 'À acheter',
    'wishlist.statusOwned': 'Déjà possédée',
    'wishlist.genChip': 'Gen {n}',
    'wishlist.sortNumAsc': 'N° ↑',
    'wishlist.sortNumDesc': 'N° ↓',
    'wishlist.sortWishedDesc': '♥ récent',
    'wishlist.sortWishedAsc': '♥ ancien',
    'wishlist.sortNameAsc': 'A → Z',
    'wishlist.sortNameDesc': 'Z → A',
    'wishlist.cardsOfTotal': '{owned}/{total} cartes',

    // Favorites / Collection screen
    'favorites.tabBinders': 'Mes binders',
    'favorites.tabArtists': 'Artistes',
    'favorites.tabTrainers': 'Dresseurs',
    'favorites.tabDuplicates': 'Doublons',
    'favorites.tabExtensions': 'Extensions',
    'favorites.regionJapan': '🇯🇵 Japon',
    'favorites.regionChina': '🇨🇳 Chine',
    'favorites.layoutOnePerPage': '1 carte / page',
    'favorites.newBinderPlaceholder': 'Nom du nouveau binder',
    'favorites.noBindersYet': 'Aucun binder pour l’instant — crée-en un ci-dessus.',
    'favorites.binderCardCountSingular': '{n} carte',
    'favorites.binderCardCountPlural': '{n} cartes',
    'favorites.layoutSheetTitle': 'Mise en page',
    'favorites.searchArtistPlaceholder': 'Chercher un artiste',
    'favorites.noArtistFound': 'Aucun artiste trouvé.',
    'favorites.cardsOfTotal': '{owned}/{total} cartes',
    'favorites.searchCardPlaceholder': 'Chercher une carte',
    'favorites.sortValue': 'Valeur',
    'favorites.sortQuantity': 'Quantité',
    'favorites.sortNameAZ': 'A-Z',
    'favorites.noResults': 'Aucun résultat.',
    'favorites.noDuplicatesYet': 'Aucun doublon pour l’instant — un doublon apparaît ici dès qu’une carte passe à 2 exemplaires ou plus.',
    'favorites.setCardsCount': '{n} cartes',
    'favorites.startPin': 'Commencer',
    'favorites.deleteBinderTitle': 'Supprimer le binder',
    'favorites.deleteConfirmMessage': 'Supprimer "{name}" ?',
    'favorites.a11yViewBinder': 'Voir le binder',
    'favorites.a11yChangeLayout': 'Changer la mise en page',
    'favorites.a11yAddCard': 'Ajouter une carte',
    'favorites.a11yRemoveCard': 'Retirer cette carte',

    // Binder slot picker (card or photo)
    'binderPicker.photoPermToast': 'Autorise l’accès à tes photos pour importer une image.',
    'binderPicker.photoImportErrToast': 'Impossible d’importer cette photo, réessaie.',
    'binderPicker.chooseCardTitle': 'Choisir une carte',
    'binderPicker.importPhotoTitle': 'Importer une photo',
    'binderPicker.modeCard': 'Carte',
    'binderPicker.modePhoto': 'Photo',
    'binderPicker.photoHint': 'Importe une photo perso pour cet emplacement — elle sera recadrée au format d’une carte.',
    'binderPicker.importing': 'Import…',
    'binderPicker.choosePhoto': 'Choisir une photo',
    'binderPicker.searchPlaceholder': 'Chercher un Pokémon (nom ou n°)',
    'binderPicker.typeToSearch': 'Tape un nom ou un numéro pour chercher.',
    'binderPicker.noCardsForPokemon': 'Aucune carte TCG connue pour ce Pokémon.',

    // Trainers panel
    'trainers.countSingular': '{n} dresseur',
    'trainers.countPlural': '{n} dresseurs',
    'trainers.searchPlaceholder': 'Chercher un dresseur',
    'trainers.notFound': 'Aucun dresseur trouvé.',
  },
  en: {
    'common.back': 'Back',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.save': 'Save',
    'common.copy': 'Copy',
    'common.error': 'Error',
    'common.copied': 'Copied',
    'common.cancel': 'Cancel',
    'common.choose': 'Choose',
    'common.all': 'All',
    'common.clear': 'Clear',
    'common.delete': 'Delete',
    'common.unpin': 'Unpin',

    'auth.login.title': 'Log in',
    'auth.login.submit': 'Log in',
    'auth.login.forgotPassword': 'Forgot password?',
    'auth.login.noAccount': 'No account? Sign up',
    'auth.login.genericErr': 'Login failed',

    'auth.signup.title': 'Create an account',
    'auth.signup.passwordPlaceholder': 'Password (min 6)',
    'auth.signup.usernamePlaceholder': 'Username (immutable, e.g. tristan-42)',
    'auth.signup.checking': 'Checking…',
    'auth.signup.available': 'Available ✓',
    'auth.signup.taken': 'Already taken',
    'auth.signup.invalidFormat': 'Invalid format',
    'auth.signup.displayNamePlaceholder': 'Display name (public)',
    'auth.signup.submit': 'Sign up',
    'auth.signup.haveAccount': 'Already have an account? Log in',
    'auth.signup.legalPrefix': 'By signing up, you accept the',
    'auth.signup.legalTerms': 'Terms',
    'auth.signup.legalAnd': 'and the',
    'auth.signup.legalPrivacy': 'privacy policy',
    'auth.signup.usernameInvalidMsg': 'Invalid username (3–30 characters, a-z 0-9 _ - only, must start with a-z or 0-9)',
    'auth.signup.usernameTakenErr': 'This username is already taken',
    'auth.signup.genericErr': 'Sign up failed',
    'auth.signup.checkEmailTitle': 'Check your inbox',
    'auth.signup.checkEmailBody': 'We sent a confirmation link to {email}. Click it to activate your account, then log in.',
    'auth.signup.backToLogin': 'Back to login',

    'settings.usernameLabel': 'Username (immutable)',
    'settings.displayNameLabel': 'Display name',
    'settings.publicProfileLabel': 'Public profile',
    'settings.darkThemeLabel': 'Dark theme',
    'settings.languageLabel': 'Language',
    'settings.paletteLabel': 'Color palette',
    'settings.animationsLabel': 'Animations',
    'settings.shareLinkLabel': 'Share link',
    'settings.feedbackAdminLabel': 'Suggestions & tickets (admin)',
    'settings.feedbackLabel': 'Suggestions & bugs',
    'settings.logout': 'Log out',
    'settings.terms': 'Terms of use',
    'settings.privacy': 'Privacy',
    'settings.trainerFallback': 'Trainer',

    'pokedex.heroTitle': 'National Pokédex',
    'pokedex.filterHint': 'Filter: {hint}',

    'search.placeholder': 'Search (name or #)',
    'search.owned': 'Owned',
    'search.missing': 'Missing',
    'search.filtersTitle': 'Filters',
    'search.statusLabel': 'Status',
    'search.sectionLabel': 'Generation / Type / Set / Rarity',
    'search.sortLabel': 'Sort',
    'search.resetFilters': 'Reset filters',
    'search.typeLabel': 'Type',
    'search.setLabel': 'Set',
    'search.setTcgTitle': 'TCG Set',
    'search.rarityLabel': 'Rarity',
    'search.generationLabel': 'Generation',
    'search.typeChip': 'Type: {value}',
    'search.typeChipCount': 'Type ({n})',
    'search.setChip': 'Set: {value}',
    'search.rarityChip': 'Rarity: {value}',
    'search.genChipCount': 'Generation ({n})',

    'cardFilter.title': 'Filter by set',
    'cardFilter.selectedSingular': '{n} set selected',
    'cardFilter.selectedPlural': '{n} sets selected',
    'cardFilter.otherSeries': 'Other',

    'pokemon.notFound': 'Unknown Pokémon',
    'pokemon.showcaseLimitToast': 'Showcase limited to {n} cards — remove one before adding another.',
    'pokemon.noCardsKnown': 'No known TCG card for this Pokémon in the database.',
    'pokemon.noRegionCards': 'No {region} card known for this Pokémon.',
    'pokemon.noCardsInSelectedSets': 'No card in the selected sets.',
    'pokemon.wishFilterActive': '♥ Wishlist filter active — tap to see all',
    'pokemon.infoBanner': 'Owned cards appear unlocked. Tap a card to make it your National Pokédex card.',
    'pokemon.chooseCardTitle': 'Choose this card',
    'pokemon.chooseCardMessage': 'Make "{cardName}" your National Pokédex card for {pokemonName}?',
    'pokemon.addedOn': 'Added on {date}',
    'pokemon.regionGlobal': 'Global',
    'pokemon.regionChinese': 'Chinese',
    'pokemon.regionJapanese': 'Japanese',

    'cardCopy.title': 'My copy',
    'cardCopy.editButton': 'Edit finish / condition',
    'cardCopy.detailsA11yLabel': 'View finish and condition',
    'cardCopy.notListedHint': 'Not listed for this card',

    'capture.rarityCaptured': '{rarityLabel} card captured',
    'capture.typeComplete': '{type} type complete!',
    'capture.milestoneTitle': '{count} {type}-type Pokémon captured!',
    'capture.dexAdded': 'New card added to the Pokédex!',
    'capture.rarityTitle': '✨ {rarityLabel}!',
    'capture.typeSubtitle': 'All {type}-type Pokémon are captured in this set',
    'capture.milestoneSubtitle': 'Keep it up!',
    'capture.raritySubtitle': 'A gem for your collection',

    'tabs.pokedex': 'National Pokédex',
    'tabs.collection': 'Collection',
    'tabs.wishlist': 'Wishlist',

    'dashboard.title': 'Dashboard',
    'dashboard.collectionValueLabel': 'Estimated value of your collection: {value}',
    'dashboard.collectionLabel': 'Collection',
    'dashboard.tradesSub': 'trades',
    'dashboard.tradesLabel': 'Trades',
    'dashboard.cardsSub': 'cards',
    'dashboard.ownedLabel': 'Owned',
    'dashboard.unpinTitle': 'Remove this goal?',
    'dashboard.unpinMessage': '{name} will no longer be tracked as a completion goal.',
    'dashboard.typesComplete': '{n}/18 types complete',
    'dashboard.gensComplete': '{n}/9 generations complete',
    'dashboard.tapForDetail': 'Tap to see the detail',
    'dashboard.stateChosen': 'Chosen',
    'dashboard.stateCaptured': 'Captured',
    'dashboard.stateSeen': 'Seen',
    'dashboard.stateRemaining': 'Remaining',
    'dashboard.stateRemainingTitle': 'Remaining to see',
    'dashboard.valueChosen': 'Value of chosen cards',
    'dashboard.valueTotalOwned': 'Total owned value',
    'dashboard.valueWishlist': 'Theoretical value of your wishlist',
    'dashboard.typeBreakdownTitle': '{type} type',
    'dashboard.noArtistsYet': 'No card with a known artist yet.',
    'dashboard.artistCardCountSingular': '{n} card',
    'dashboard.artistCardCountPlural': '{n} cards',
    'dashboard.variantMega': 'Mega Evolutions',
    'dashboard.variantAlolan': 'Alolan Forms',
    'dashboard.variantGalarian': 'Galarian Forms',
    'dashboard.variantHisuian': 'Hisuian Forms',
    'dashboard.variantPaldean': 'Paldean Forms',
    'dashboard.variantRotom': 'Rotom Forms',
    'dashboard.variantDeoxys': 'Deoxys Forms',
    'dashboard.variantGigamax': 'Dynamax / Gigamax',
    'dashboard.badgesLabel': 'Badges',
    'dashboard.vitrineTitle': 'Showcase',

    'newSetBanner.newSet': 'New set: {label}',
    'newSetBanner.view': 'View',
    'newSetBanner.moreSingular': '+{n} more recent set',
    'newSetBanner.morePlural': '+{n} more recent sets',

    'setGoalPicker.title': 'Completion goals',
    'setGoalPicker.searchPlaceholder': 'Search a set',
    'setGoalPicker.empty': 'No set found.',
    'setGoalPicker.cardsCount': '{n} cards',

    'statBreakdown.owned': 'Owned',
    'statBreakdown.missing': 'Missing',

    'statsTabs.title': 'Statistics',
    'statsTabs.progress': 'Progress',
    'statsTabs.generation': 'Generation',
    'statsTabs.type': 'Type',
    'statsTabs.variants': 'Forms',
    'statsTabs.artists': 'Artists',

    'allBadges.title': 'All badges ({n})',
    'badgeDetail.unlocked': 'Unlocked',
    'badgeDetail.locked': 'Locked',
    'badgeDetail.close': 'Close',

    'wishlist.emptyTitle': 'No card in your wishlist',
    'wishlist.emptyHint': 'Add some from a Pokémon detail page (♥ icon).',
    'wishlist.noResults': 'No result with these filters.',
    'wishlist.cardsInWishlistSingular': '{n} card in wishlist',
    'wishlist.cardsInWishlistPlural': '{n} cards in wishlist',
    'wishlist.alreadyOwnedSingular': ' · {n} already owned',
    'wishlist.alreadyOwnedPlural': ' · {n} already owned',
    'wishlist.searchPlaceholder': 'Search (name, set, #)',
    'wishlist.filtersAndSort': 'Filters & sort',
    'wishlist.statusAll': 'All',
    'wishlist.statusNotOwned': 'To buy',
    'wishlist.statusOwned': 'Already owned',
    'wishlist.genChip': 'Gen {n}',
    'wishlist.sortNumAsc': 'N° ↑',
    'wishlist.sortNumDesc': 'N° ↓',
    'wishlist.sortWishedDesc': '♥ recent',
    'wishlist.sortWishedAsc': '♥ oldest',
    'wishlist.sortNameAsc': 'A → Z',
    'wishlist.sortNameDesc': 'Z → A',
    'wishlist.cardsOfTotal': '{owned}/{total} cards',

    'favorites.tabBinders': 'My binders',
    'favorites.tabArtists': 'Artists',
    'favorites.tabTrainers': 'Trainers',
    'favorites.tabDuplicates': 'Duplicates',
    'favorites.tabExtensions': 'Sets',
    'favorites.regionJapan': '🇯🇵 Japan',
    'favorites.regionChina': '🇨🇳 China',
    'favorites.layoutOnePerPage': '1 card / page',
    'favorites.newBinderPlaceholder': 'New binder name',
    'favorites.noBindersYet': 'No binder yet — create one above.',
    'favorites.binderCardCountSingular': '{n} card',
    'favorites.binderCardCountPlural': '{n} cards',
    'favorites.layoutSheetTitle': 'Layout',
    'favorites.searchArtistPlaceholder': 'Search an artist',
    'favorites.noArtistFound': 'No artist found.',
    'favorites.cardsOfTotal': '{owned}/{total} cards',
    'favorites.searchCardPlaceholder': 'Search a card',
    'favorites.sortValue': 'Value',
    'favorites.sortQuantity': 'Quantity',
    'favorites.sortNameAZ': 'A-Z',
    'favorites.noResults': 'No result.',
    'favorites.noDuplicatesYet': 'No duplicate yet — one appears here as soon as a card reaches 2 or more copies.',
    'favorites.setCardsCount': '{n} cards',
    'favorites.startPin': 'Start',
    'favorites.deleteBinderTitle': 'Delete binder',
    'favorites.deleteConfirmMessage': 'Delete "{name}"?',
    'favorites.a11yViewBinder': 'View binder',
    'favorites.a11yChangeLayout': 'Change layout',
    'favorites.a11yAddCard': 'Add a card',
    'favorites.a11yRemoveCard': 'Remove this card',

    'binderPicker.photoPermToast': 'Allow access to your photos to import an image.',
    'binderPicker.photoImportErrToast': 'Couldn’t import this photo, try again.',
    'binderPicker.chooseCardTitle': 'Choose a card',
    'binderPicker.importPhotoTitle': 'Import a photo',
    'binderPicker.modeCard': 'Card',
    'binderPicker.modePhoto': 'Photo',
    'binderPicker.photoHint': 'Import a personal photo for this slot — it’ll be cropped to a card’s shape.',
    'binderPicker.importing': 'Importing…',
    'binderPicker.choosePhoto': 'Choose a photo',
    'binderPicker.searchPlaceholder': 'Search a Pokémon (name or #)',
    'binderPicker.typeToSearch': 'Type a name or number to search.',
    'binderPicker.noCardsForPokemon': 'No known TCG card for this Pokémon.',

    'trainers.countSingular': '{n} trainer',
    'trainers.countPlural': '{n} trainers',
    'trainers.searchPlaceholder': 'Search a trainer',
    'trainers.notFound': 'No trainer found.',
  },
} as const;

export type StringKey = keyof typeof STRINGS['fr'];
