// Flat FR/EN dictionary for the app's UI text. Only covers the screens/components
// translated so far (auth, Pokédex browsing, Pokémon detail, Settings) — see the
// language-toggle plan doc for what's still French-only regardless of locale.
// Extend this file (add keys to both `fr` and `en`) as more screens get translated;
// no architecture change needed for that.
export const STRINGS = {
  fr: {
    // Common
    'common.back': 'Retour',
    'common.email': 'Email',
    'common.password': 'Mot de passe',
    'common.save': 'Enregistrer',
    'common.copy': 'Copier',
    'common.error': 'Erreur',
    'common.copied': 'Copié',
    'common.cancel': 'Annuler',
    'common.choose': 'Choisir',
    'common.all': 'Tous',
    'common.clear': 'Effacer',

    // Auth — login
    'auth.login.title': 'Connexion',
    'auth.login.submit': 'Se connecter',
    'auth.login.forgotPassword': 'Mot de passe oublié ?',
    'auth.login.noAccount': "Pas de compte ? S'inscrire",
    'auth.login.genericErr': 'Échec de la connexion',

    // Auth — signup
    'auth.signup.title': 'Créer un compte',
    'auth.signup.passwordPlaceholder': 'Mot de passe (min 6)',
    'auth.signup.usernamePlaceholder': 'Username (immutable, ex: tristan-42)',
    'auth.signup.checking': 'Vérification…',
    'auth.signup.available': 'Disponible ✓',
    'auth.signup.taken': 'Déjà pris',
    'auth.signup.invalidFormat': 'Format invalide',
    'auth.signup.displayNamePlaceholder': 'Nom affiché (public)',
    'auth.signup.submit': "S'inscrire",
    'auth.signup.haveAccount': 'Déjà un compte ? Se connecter',
    'auth.signup.legalPrefix': "En t'inscrivant, tu acceptes les",
    'auth.signup.legalTerms': 'CGU',
    'auth.signup.legalAnd': 'et la',
    'auth.signup.legalPrivacy': 'politique de confidentialité',
    'auth.signup.usernameInvalidMsg': 'Username invalide (3–30 caractères, a-z 0-9 _ - uniquement, doit commencer par a-z ou 0-9)',
    'auth.signup.usernameTakenErr': 'Ce username est déjà pris',
    'auth.signup.genericErr': 'Inscription échouée',
    'auth.signup.checkEmailTitle': 'Vérifie ta boîte mail',
    'auth.signup.checkEmailBody': 'On a envoyé un lien de confirmation à {email}. Clique dessus pour activer ton compte, puis connecte-toi.',
    'auth.signup.backToLogin': 'Retour à la connexion',

    // Settings
    'settings.usernameLabel': 'Username (immuable)',
    'settings.displayNameLabel': 'Nom affiché',
    'settings.publicProfileLabel': 'Profil public',
    'settings.darkThemeLabel': 'Thème sombre',
    'settings.languageLabel': 'Langue',
    'settings.paletteLabel': 'Palette de couleurs',
    'settings.animationsLabel': 'Animations',
    'settings.shareLinkLabel': 'Lien de partage',
    'settings.feedbackAdminLabel': 'Suggestions & tickets (admin)',
    'settings.feedbackLabel': 'Suggestions & bugs',
    'settings.logout': 'Se déconnecter',
    'settings.terms': "Conditions d'utilisation",
    'settings.privacy': 'Confidentialité',
    'settings.trainerFallback': 'Dresseur',

    // Pokédex screen
    'pokedex.heroTitle': 'Pokédex National',
    'pokedex.filterHint': 'Filtre : {hint}',

    // Search / filter bar
    'search.placeholder': 'Rechercher (nom ou n°)',
    'search.owned': 'Possédés',
    'search.missing': 'Manquants',
    'search.filtersTitle': 'Filtres',
    'search.statusLabel': 'Statut',
    'search.sectionLabel': 'Génération / Type / Set / Rareté',
    'search.sortLabel': 'Tri',
    'search.resetFilters': 'Réinitialiser les filtres',
    'search.typeLabel': 'Type',
    'search.setLabel': 'Set',
    'search.setTcgTitle': 'Set TCG',
    'search.rarityLabel': 'Rareté',
    'search.generationLabel': 'Génération',
    'search.typeChip': 'Type: {value}',
    'search.typeChipCount': 'Type ({n})',
    'search.setChip': 'Set: {value}',
    'search.rarityChip': 'Rareté: {value}',
    'search.genChipCount': 'Génération ({n})',

    // Card filter tree (extension filter)
    'cardFilter.title': 'Filtrer par extension',
    'cardFilter.selectedSingular': '{n} set sélectionné',
    'cardFilter.selectedPlural': '{n} sets sélectionnés',
    'cardFilter.otherSeries': 'Autres',

    // Pokémon detail
    'pokemon.notFound': 'Pokémon inconnu',
    'pokemon.showcaseLimitToast': 'Vitrine limitée à {n} cartes — retire-en une avant d’en ajouter une autre.',
    'pokemon.noCardsKnown': 'Aucune carte TCG connue pour ce Pokémon dans la base.',
    'pokemon.noRegionCards': 'Aucune carte {region} connue pour ce Pokémon.',
    'pokemon.noCardsInSelectedSets': 'Aucune carte dans les extensions sélectionnées.',
    'pokemon.wishFilterActive': '♥ Filtre wish actif — tap pour tout voir',
    'pokemon.infoBanner': 'Les cartes possédées apparaissent déverrouillées. Touche une carte pour en faire ta carte choisie du Pokédex national.',
    'pokemon.chooseCardTitle': 'Choisir cette carte',
    'pokemon.chooseCardMessage': 'Faire de « {cardName} » ta carte choisie du Pokédex national pour {pokemonName} ?',
    'pokemon.addedOn': 'Ajoutée le {date}',
    'pokemon.regionGlobal': 'Global',
    'pokemon.regionChinese': 'Chinois',
    'pokemon.regionJapanese': 'Japonais',

    // Card copy sheet (finish/condition editor)
    'cardCopy.title': 'Ma copie',
    'cardCopy.editButton': 'Modifier finition / état',
    'cardCopy.detailsA11yLabel': 'Voir finition et état',
    'cardCopy.notListedHint': 'Non listée pour cette carte',
  },
  en: {
    'common.back': 'Back',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.save': 'Save',
    'common.copy': 'Copy',
    'common.error': 'Error',
    'common.copied': 'Copied',
    'common.cancel': 'Cancel',
    'common.choose': 'Choose',
    'common.all': 'All',
    'common.clear': 'Clear',

    'auth.login.title': 'Log in',
    'auth.login.submit': 'Log in',
    'auth.login.forgotPassword': 'Forgot password?',
    'auth.login.noAccount': 'No account? Sign up',
    'auth.login.genericErr': 'Login failed',

    'auth.signup.title': 'Create an account',
    'auth.signup.passwordPlaceholder': 'Password (min 6)',
    'auth.signup.usernamePlaceholder': 'Username (immutable, e.g. tristan-42)',
    'auth.signup.checking': 'Checking…',
    'auth.signup.available': 'Available ✓',
    'auth.signup.taken': 'Already taken',
    'auth.signup.invalidFormat': 'Invalid format',
    'auth.signup.displayNamePlaceholder': 'Display name (public)',
    'auth.signup.submit': 'Sign up',
    'auth.signup.haveAccount': 'Already have an account? Log in',
    'auth.signup.legalPrefix': 'By signing up, you accept the',
    'auth.signup.legalTerms': 'Terms',
    'auth.signup.legalAnd': 'and the',
    'auth.signup.legalPrivacy': 'privacy policy',
    'auth.signup.usernameInvalidMsg': 'Invalid username (3–30 characters, a-z 0-9 _ - only, must start with a-z or 0-9)',
    'auth.signup.usernameTakenErr': 'This username is already taken',
    'auth.signup.genericErr': 'Sign up failed',
    'auth.signup.checkEmailTitle': 'Check your inbox',
    'auth.signup.checkEmailBody': 'We sent a confirmation link to {email}. Click it to activate your account, then log in.',
    'auth.signup.backToLogin': 'Back to login',

    'settings.usernameLabel': 'Username (immutable)',
    'settings.displayNameLabel': 'Display name',
    'settings.publicProfileLabel': 'Public profile',
    'settings.darkThemeLabel': 'Dark theme',
    'settings.languageLabel': 'Language',
    'settings.paletteLabel': 'Color palette',
    'settings.animationsLabel': 'Animations',
    'settings.shareLinkLabel': 'Share link',
    'settings.feedbackAdminLabel': 'Suggestions & tickets (admin)',
    'settings.feedbackLabel': 'Suggestions & bugs',
    'settings.logout': 'Log out',
    'settings.terms': 'Terms of use',
    'settings.privacy': 'Privacy',
    'settings.trainerFallback': 'Trainer',

    'pokedex.heroTitle': 'National Pokédex',
    'pokedex.filterHint': 'Filter: {hint}',

    'search.placeholder': 'Search (name or #)',
    'search.owned': 'Owned',
    'search.missing': 'Missing',
    'search.filtersTitle': 'Filters',
    'search.statusLabel': 'Status',
    'search.sectionLabel': 'Generation / Type / Set / Rarity',
    'search.sortLabel': 'Sort',
    'search.resetFilters': 'Reset filters',
    'search.typeLabel': 'Type',
    'search.setLabel': 'Set',
    'search.setTcgTitle': 'TCG Set',
    'search.rarityLabel': 'Rarity',
    'search.generationLabel': 'Generation',
    'search.typeChip': 'Type: {value}',
    'search.typeChipCount': 'Type ({n})',
    'search.setChip': 'Set: {value}',
    'search.rarityChip': 'Rarity: {value}',
    'search.genChipCount': 'Generation ({n})',

    'cardFilter.title': 'Filter by set',
    'cardFilter.selectedSingular': '{n} set selected',
    'cardFilter.selectedPlural': '{n} sets selected',
    'cardFilter.otherSeries': 'Other',

    'pokemon.notFound': 'Unknown Pokémon',
    'pokemon.showcaseLimitToast': 'Showcase limited to {n} cards — remove one before adding another.',
    'pokemon.noCardsKnown': 'No known TCG card for this Pokémon in the database.',
    'pokemon.noRegionCards': 'No {region} card known for this Pokémon.',
    'pokemon.noCardsInSelectedSets': 'No card in the selected sets.',
    'pokemon.wishFilterActive': '♥ Wishlist filter active — tap to see all',
    'pokemon.infoBanner': 'Owned cards appear unlocked. Tap a card to make it your National Pokédex card.',
    'pokemon.chooseCardTitle': 'Choose this card',
    'pokemon.chooseCardMessage': 'Make "{cardName}" your National Pokédex card for {pokemonName}?',
    'pokemon.addedOn': 'Added on {date}',
    'pokemon.regionGlobal': 'Global',
    'pokemon.regionChinese': 'Chinese',
    'pokemon.regionJapanese': 'Japanese',

    'cardCopy.title': 'My copy',
    'cardCopy.editButton': 'Edit finish / condition',
    'cardCopy.detailsA11yLabel': 'View finish and condition',
    'cardCopy.notListedHint': 'Not listed for this card',
  },
} as const;

export type StringKey = keyof typeof STRINGS['fr'];
